### ISSUE TITLE
How does "diversion_layer" work in the encoder?

### ISSUE THREAD

**Issue by CabbageSong** [oss-roettger/HR_Encoder#1]
Hi @oss-roettger !

Thanks for the great work on the encoder of StyleGAN v2. I found the discriminator is changed and the attribute "diversion_layer" is added. I wonder what the new attribute does in your code and whether the discriminator is necessary in encoding.

**Comment by oss-roettger** [comment]
HR_Encoder uses intermediate layer outputs of the discriminator to preserve high level image features during the encoding process (instead of VGG16 intermediate features used in the original encoding paper). The „diversion_layer“ parameter defines the intermediate layer of the discriminator to be used (diversion_layes=4 works fine, but you could also try other layers). diversion_layer=n is the last but n-th layer of the discriminator, e.g. diversion_layer=0 would be the original output of the discriminator.

**Comment by CabbageSong** [comment]
Thank you for the generous reply!  I tried to get the latent code only with the image loss, but it doesn't work well (Which makes blurred images). I am still curious with the regulation loss, and I wonder how it works in the network.
